{
    'name': 'IT Helpdesk UI V2',
    'version': '15.0.1.0.0',
    'summary': 'Sistem tiket IT Helpdesk dengan priority engine, SLA, work order, dan change request.',
    'category': 'Services/Helpdesk',
    'author': 'Indra Febriansyah',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'portal',
        'resource',
        'hr',
        'board',
    ],
    'data': [
        'security/helpdesk_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/helpdesk_priority_question_data.xml',
        'data/helpdesk_priority_matrix_data.xml',
        'data/helpdesk_sla_data.xml',
        'data/helpdesk_sla_status_data.xml',
        'data/mail_template_data.xml',
        'data/helpdesk_email_template_data.xml',
        'data/helpdesk_change_request_email_template_data.xml',
        'data/ir_cron_data.xml',
        'views/helpdesk_dashboard_views.xml',
        'data/helpdesk_dashboard_data.xml',
        'views/helpdesk_service_views.xml',
        'views/helpdesk_priority_views.xml',
        'views/helpdesk_sla_views.xml',
        'views/helpdesk_sla_status_views.xml',
        'views/helpdesk_team_views.xml',
        'views/helpdesk_ticket_views.xml',
        'views/helpdesk_work_order_views.xml',
        'views/helpdesk_create_ticket_views.xml',
        'views/helpdesk_my_ticket_views.xml',
        'views/helpdesk_change_request_views.xml',
        'views/helpdesk_keyword_views.xml',
        'views/helpdesk_user_views.xml',
        'views/helpdesk_knowledge_views.xml',
        'wizard/helpdesk_ticket_reassign_wizard_views.xml',
        'wizard/helpdesk_ticket_reject_wizard_views.xml',
        'report/helpdesk_report_views.xml',

        'views/helpdesk_menus.xml',
        'views/website_helpdesk_ticket_templates.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'it_helpdesk_v2/static/src/js/jakarta_clock.js',
            'it_helpdesk_v2/static/src/js/helpdesk_dashboard.js',
            'it_helpdesk_v2/static/src/js/helpdesk_dashboard_drilldown.js',
            'it_helpdesk_v2/static/src/scss/helpdesk_dashboard.scss',
            # 'it_helpdesk_v2/static/src/scss/enterprise_theme.scss',
        ],

        'web.assets_qweb': [
            'it_helpdesk_v2/static/src/xml/helpdesk_dashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
